version: '3'

services:
  app:
    image: jftanner/flax
    build: .
    container_name: flax
    restart: unless-stopped
    ports:
    - 8081:8081
    environment:
    - NODE_ENV=production
    - PORT=8081
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_PASSWORD: testPass
      POSTGRES_USER: devon
      POSTGRES_DB: flax_db
      
